name: Build KRunner Plugins

on:
  push:
    branches:
      - main
      - github_actions
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish-version:
        description: "new version that should get published"
        required: true
permissions:
  contents: write

jobs:
  build-and-publish:
    uses: kas-cor/actions/.github/workflows/plugin_ci_publish.yaml@main
    with:
      publish-version: ${{ inputs.publish-version }}
